# Generated by Django 2.0.2 on 2018-04-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cp',
            field=models.ImageField(upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(upload_to='pic_folder/'),
        ),
    ]
