# Generated by Django 2.0.2 on 2018-04-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180410_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cp',
            field=models.ImageField(upload_to='images/cp/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(upload_to='images/dp/'),
        ),
    ]
