# Generated by Django 2.0.2 on 2018-04-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
    ]
